### ISSUE TITLE
account_balance_migrate_operation review :  only update the balance of the account

### ISSUE THREAD

**Issue by clar** [bitsuperlab/cpp-play2#36]
https://github.com/bitsuperlab/cpp-play2/commit/be2901aea982d8af853cc4b90e2c09de62fb121d#comments

**Comment by clar** [comment]
https://github.com/bitsuperlab/cpp-play2/blob/play/tests/common/database_fixture.cpp#L189

**Comment by hackfisher** [comment]
https://github.com/bitsuperlab/cpp-play2/commit/05f7c7aad5922115eeb2ea9973a1c81dc5ddf73e
